// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SampleDto } from "./SampleDto";

/**
 * DTO de l'event `metrics-batch`. La définition TypeScript est générée
 * par `cargo xtask gen-types` vers `frontend/src/ipc/bindings/`.
 */
export type BatchDto = { source: string, 
/**
 * Millisecondes epoch (u64 côté Rust, number côté JSON/TS).
 */
ts_ms: number, samples: Array<SampleDto>, };
