// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectorCapability } from "./CollectorCapability";

/**
 * Ce qu'une source sait fournir, par collecteur, établi au `probe()`.
 * L'UI s'en sert pour n'afficher que les widgets pertinents.
 */
export type Capabilities = { 
/**
 * collecteur → détail (ex. "cpu" → {available: true, details: {"cores": "16", "rapl": "true"}})
 */
collectors: { [key in string]: CollectorCapability }, };
