// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollectorCapability = { available: boolean, 
/**
 * Raison si indisponible (affichable en tooltip).
 */
reason?: string, 
/**
 * Détails si disponible (nb de cœurs, RAPL présent…).
 */
details: { [key in string]: string }, };
