// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Une série de la fenêtre chaude (points des ~10 dernières minutes).
 */
export type HotSeriesDto = { metric: string, labels: { [key in string]: string }, ts_ms: Array<number>, values: Array<number>, };
