// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Une ligne de la table des processus (miroir TS généré par ts-rs).
 * `cpu_pct` est en % d'un cœur, convention htop.
 */
export type ProcessRowDto = { pid: number, ppid: number, name: string, user: string, state: string, cpu_pct: number, rss_bytes: number, cmdline: string, };
