// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueDto } from "./ValueDto";

export type SampleDto = { metric: string, value: ValueDto, labels: { [key in string]: string }, };
