// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValueDto = { "kind": "gauge", "v": number } | { "kind": "counter", "v": number } | { "kind": "text", "v": string };
